package io.github.khanr1.tedscraper.r208

package types


import cats.Show

enum CountryCode {
  case AF, AX, AL, DZ, AS, AD, AO, AI, AQ, AG, AR,
    AM, AW, AU, AT, AZ, BS, BH, BD, BB, BY,
    BE, BZ, BJ, BM, BT, BO, BQ, BA, BW, BV,
    BR, IO, BN, BG, BF, BI, KH, CM, CA, CV,
    KY, CF, TD, CL, CN, CX, CC, CO, KM, CG,
    CD, CK, CR, CI, HR, CU, CW, CY, CZ, DK,
    DJ, DM, DO, EC, EG, SV, GQ, ER, EE, SZ,
    ET, FK, FO, FJ, FI, FR, GF, PF, TF, GA,
    GM, GE, DE, GH, GI, GR, GL, GD, GP, GU,
    GT, GG, GN, GW, GY, HT, HM, VA, HN, HK,
    HU, IS, IN, ID, IR, IQ, IE, IM, IL, IT,
    JM, JP, JE, JO, KZ, KE, KI, KP, KR, KW,
    KG, LA, LV, LB, LS, LR, LY, LI, LT, LU,
    MO, MG, MW, MY, MV, ML, MT, MH, MQ, MR,
    MU, YT, MX, FM, MD, MC, MN, ME, MS, MA,
    MZ, MM, NA, NR, NP, NL, NC, NZ, NI, NE,
    NG, NU, NF, MK, MP, NO, OM, PK, PW, PS,
    PA, PG, PY, PE, PH, PN, PL, PT, PR, QA,
    RE, RO, RU, RW, BL, SH, KN, LC, MF, PM,
    VC, WS, SM, ST, SA, SN, RS, SC, SL, SG,
    SX, SK, SI, SB, SO, ZA, GS, SS, ES, LK,
    SD, SR, SJ, SE, CH, SY, TW, TJ, TZ, TH,
    TL, TG, TK, TO, TT, TN, TR, TM, TC, TV,
    UG, UA, AE, UK, US, UM, UY, UZ, VU, VE,
    VN, VG, VI, WF, EH, YE, ZM, ZW, Unknown
}

object CountryCode {
  import CountryCode.*

  val fullNames: Map[CountryCode, String] = Map(
    AD -> "Andorra",
    AE -> "United Arab Emirates",
    AF -> "Afghanistan",
    AG -> "Antigua and Barbuda",
    AI -> "Anguilla",
    AL -> "Albania",
    AM -> "Armenia",
    AO -> "Angola",
    AQ -> "Antarctica",
    AR -> "Argentina",
    AS -> "American Samoa",
    AT -> "Austria",
    AU -> "Australia",
    AW -> "Aruba",
    AX -> "Åland Islands",
    AZ -> "Azerbaijan",
    BA -> "Bosnia and Herzegovina",
    BB -> "Barbados",
    BD -> "Bangladesh",
    BE -> "Belgium",
    BF -> "Burkina Faso",
    BG -> "Bulgaria",
    BH -> "Bahrain",
    BI -> "Burundi",
    BJ -> "Benin",
    BL -> "Saint Barthélemy",
    BM -> "Bermuda",
    BN -> "Brunei Darussalam",
    BO -> "Bolivia (Plurinational State of)",
    BQ -> "Bonaire, Sint Eustatius and Saba",
    BR -> "Brazil",
    BS -> "Bahamas",
    BT -> "Bhutan",
    BV -> "Bouvet Island",
    BW -> "Botswana",
    BY -> "Belarus",
    BZ -> "Belize",
    CA -> "Canada",
    CC -> "Cocos (Keeling) Islands",
    CD -> "Congo (Democratic Republic of the)",
    CF -> "Central African Republic",
    CG -> "Congo",
    CH -> "Switzerland",
    CI -> "Côte d'Ivoire",
    CK -> "Cook Islands",
    CL -> "Chile",
    CM -> "Cameroon",
    CN -> "China",
    CO -> "Colombia",
    CR -> "Costa Rica",
    CU -> "Cuba",
    CV -> "Cabo Verde",
    CW -> "Curaçao",
    CX -> "Christmas Island",
    CY -> "Cyprus",
    CZ -> "Czechia",
    DE -> "Germany",
    DJ -> "Djibouti",
    DK -> "Denmark",
    DM -> "Dominica",
    DO -> "Dominican Republic",
    DZ -> "Algeria",
    EC -> "Ecuador",
    EE -> "Estonia",
    EG -> "Egypt",
    EH -> "Western Sahara",
    ER -> "Eritrea",
    ES -> "Spain",
    ET -> "Ethiopia",
    FI -> "Finland",
    FJ -> "Fiji",
    FK -> "Falkland Islands (Malvinas)",
    FM -> "Micronesia (Federated States of)",
    FO -> "Faroe Islands",
    FR -> "France",
    GA -> "Gabon",
    GD -> "Grenada",
    GE -> "Georgia",
    GF -> "French Guiana",
    GG -> "Guernsey",
    GH -> "Ghana",
    GI -> "Gibraltar",
    GL -> "Greenland",
    GM -> "Gambia",
    GN -> "Guinea",
    GP -> "Guadeloupe",
    GQ -> "Equatorial Guinea",
    GR -> "Greece",
    GS -> "South Georgia and the South Sandwich Islands",
    GT -> "Guatemala",
    GU -> "Guam",
    GW -> "Guinea-Bissau",
    GY -> "Guyana",
    HK -> "Hong Kong",
    HM -> "Heard Island and McDonald Islands",
    HN -> "Honduras",
    HR -> "Croatia",
    HT -> "Haiti",
    HU -> "Hungary",
    ID -> "Indonesia",
    IE -> "Ireland",
    IL -> "Israel",
    IM -> "Isle of Man",
    IN -> "India",
    IO -> "British Indian Ocean Territory",
    IQ -> "Iraq",
    IR -> "Iran (Islamic Republic of)",
    IS -> "Iceland",
    IT -> "Italy",
    JE -> "Jersey",
    JM -> "Jamaica",
    JO -> "Jordan",
    JP -> "Japan",
    KE -> "Kenya",
    KG -> "Kyrgyzstan",
    KH -> "Cambodia",
    KI -> "Kiribati",
    KM -> "Comoros",
    KN -> "Saint Kitts and Nevis",
    KP -> "Korea (Democratic People's Republic of)",
    KR -> "Korea (Republic of)",
    KW -> "Kuwait",
    KY -> "Cayman Islands",
    KZ -> "Kazakhstan",
    LA -> "Lao People's Democratic Republic",
    LB -> "Lebanon",
    LC -> "Saint Lucia",
    LI -> "Liechtenstein",
    LK -> "Sri Lanka",
    LR -> "Liberia",
    LS -> "Lesotho",
    LT -> "Lithuania",
    LU -> "Luxembourg",
    LV -> "Latvia",
    LY -> "Libya",
    MA -> "Morocco",
    MC -> "Monaco",
    MD -> "Moldova (Republic of)",
    ME -> "Montenegro",
    MF -> "Saint Martin (French part)",
    MG -> "Madagascar",
    MH -> "Marshall Islands",
    MK -> "North Macedonia",
    ML -> "Mali",
    MM -> "Myanmar",
    MN -> "Mongolia",
    MO -> "Macao",
    MP -> "Northern Mariana Islands",
    MQ -> "Martinique",
    MR -> "Mauritania",
    MS -> "Montserrat",
    MT -> "Malta",
    MU -> "Mauritius",
    MV -> "Maldives",
    MW -> "Malawi",
    MX -> "Mexico",
    MY -> "Malaysia",
    MZ -> "Mozambique",
    NA -> "Namibia",
    NC -> "New Caledonia",
    NE -> "Niger",
    NF -> "Norfolk Island",
    NG -> "Nigeria",
    NI -> "Nicaragua",
    NL -> "Netherlands",
    NO -> "Norway",
    NP -> "Nepal",
    NR -> "Nauru",
    NU -> "Niue",
    NZ -> "New Zealand",
    OM -> "Oman",
    PA -> "Panama",
    PE -> "Peru",
    PF -> "French Polynesia",
    PG -> "Papua New Guinea",
    PH -> "Philippines",
    PK -> "Pakistan",
    PL -> "Poland",
    PM -> "Saint Pierre and Miquelon",
    PN -> "Pitcairn",
    PR -> "Puerto Rico",
    PS -> "Palestine, State of",
    PT -> "Portugal",
    PW -> "Palau",
    PY -> "Paraguay",
    QA -> "Qatar",
    RE -> "Réunion",
    RO -> "Romania",
    RS -> "Serbia",
    RU -> "Russian Federation",
    RW -> "Rwanda",
    SA -> "Saudi Arabia",
    SB -> "Solomon Islands",
    SC -> "Seychelles",
    SD -> "Sudan",
    SE -> "Sweden",
    SG -> "Singapore",
    SH -> "Saint Helena, Ascension and Tristan da Cunha",
    SI -> "Slovenia",
    SJ -> "Svalbard and Jan Mayen",
    SK -> "Slovakia",
    SL -> "Sierra Leone",
    SM -> "San Marino",
    SN -> "Senegal",
    SO -> "Somalia",
    SR -> "Suriname",
    SS -> "South Sudan",
    ST -> "Sao Tome and Principe",
    SV -> "El Salvador",
    SX -> "Sint Maarten (Dutch part)",
    SY -> "Syrian Arab Republic",
    SZ -> "Eswatini",
    TC -> "Turks and Caicos Islands",
    TD -> "Chad",
    TF -> "French Southern Territories",
    TG -> "Togo",
    TH -> "Thailand",
    TJ -> "Tajikistan",
    TK -> "Tokelau",
    TL -> "Timor-Leste",
    TM -> "Turkmenistan",
    TN -> "Tunisia",
    TO -> "Tonga",
    TR -> "Türkiye",
    TT -> "Trinidad and Tobago",
    TV -> "Tuvalu",
    TW -> "Taiwan (Province of China)",
    TZ -> "Tanzania, United Republic of",
    UA -> "Ukraine",
    UG -> "Uganda",
    UK -> "United Kingdom",
    UM -> "United States Minor Outlying Islands",
    US -> "United States",
    UY -> "Uruguay",
    UZ -> "Uzbekistan",
    VA -> "Holy See",
    VC -> "Saint Vincent and the Grenadines",
    VE -> "Venezuela (Bolivarian Republic of)",
    VG -> "Virgin Islands (British)",
    VI -> "Virgin Islands (U.S.)",
    VN -> "Viet Nam",
    VU -> "Vanuatu",
    WF -> "Wallis and Futuna",
    WS -> "Samoa",
    YE -> "Yemen",
    YT -> "Mayotte",
    ZA -> "South Africa",
    ZM -> "Zambia",
    ZW -> "Zimbabwe",
    Unknown -> "Unknown"
  )

  val alpha3: Map[CountryCode, String] = Map(
    AD -> "AND",
    AE -> "ARE",
    AF -> "AFG",
    AG -> "ATG",
    AI -> "AIA",
    AL -> "ALB",
    AM -> "ARM",
    AO -> "AGO",
    AQ -> "ATA",
    AR -> "ARG",
    AS -> "ASM",
    AT -> "AUT",
    AU -> "AUS",
    AW -> "ABW",
    AX -> "ALA",
    AZ -> "AZE",
    BA -> "BIH",
    BB -> "BRB",
    BD -> "BGD",
    BE -> "BEL",
    BF -> "BFA",
    BG -> "BGR",
    BH -> "BHR",
    BI -> "BDI",
    BJ -> "BEN",
    BL -> "BLM",
    BM -> "BMU",
    BN -> "BRN",
    BO -> "BOL",
    BQ -> "BES",
    BR -> "BRA",
    BS -> "BHS",
    BT -> "BTN",
    BV -> "BVT",
    BW -> "BWA",
    BY -> "BLR",
    BZ -> "BLZ",
    CA -> "CAN",
    CC -> "CCK",
    CD -> "COD",
    CF -> "CAF",
    CG -> "COG",
    CH -> "CHE",
    CI -> "CIV",
    CK -> "COK",
    CL -> "CHL",
    CM -> "CMR",
    CN -> "CHN",
    CO -> "COL",
    CR -> "CRI",
    CU -> "CUB",
    CV -> "CPV",
    CW -> "CUW",
    CX -> "CXR",
    CY -> "CYP",
    CZ -> "CZE",
    DE -> "DEU",
    DJ -> "DJI",
    DK -> "DNK",
    DM -> "DMA",
    DO -> "DOM",
    DZ -> "DZA",
    EC -> "ECU",
    EE -> "EST",
    EG -> "EGY",
    EH -> "ESH",
    ER -> "ERI",
    ES -> "ESP",
    ET -> "ETH",
    FI -> "FIN",
    FJ -> "FJI",
    FK -> "FLK",
    FM -> "FSM",
    FO -> "FRO",
    FR -> "FRA",
    GA -> "GAB",
    UK -> "GBR", // UK special case
    GD -> "GRD",
    GE -> "GEO",
    GF -> "GUF",
    GG -> "GGY",
    GH -> "GHA",
    GI -> "GIB",
    GL -> "GRL",
    GM -> "GMB",
    GN -> "GIN",
    GP -> "GLP",
    GQ -> "GNQ",
    GR -> "GRC",
    GT -> "GTM",
    GU -> "GUM",
    GW -> "GNB",
    GY -> "GUY",
    HK -> "HKG",
    HM -> "HMD",
    HN -> "HND",
    HR -> "HRV",
    HT -> "HTI",
    HU -> "HUN",
    ID -> "IDN",
    IE -> "IRL",
    IL -> "ISR",
    IM -> "IMN",
    IN -> "IND",
    IO -> "IOT",
    IQ -> "IRQ",
    IR -> "IRN",
    IS -> "ISL",
    IT -> "ITA",
    JE -> "JEY",
    JM -> "JAM",
    JO -> "JOR",
    JP -> "JPN",
    KE -> "KEN",
    KG -> "KGZ",
    KH -> "KHM",
    KI -> "KIR",
    KM -> "COM",
    KN -> "KNA",
    KP -> "PRK",
    KR -> "KOR",
    KW -> "KWT",
    KY -> "CYM",
    KZ -> "KAZ",
    LA -> "LAO",
    LB -> "LBN",
    LC -> "LCA",
    LI -> "LIE",
    LK -> "LKA",
    LR -> "LBR",
    LS -> "LSO",
    LT -> "LTU",
    LU -> "LUX",
    LV -> "LVA",
    LY -> "LBY",
    MA -> "MAR",
    MC -> "MCO",
    MD -> "MDA",
    ME -> "MNE",
    MF -> "MAF",
    MG -> "MDG",
    MH -> "MHL",
    MK -> "MKD",
    ML -> "MLI",
    MM -> "MMR",
    MN -> "MNG",
    MO -> "MAC",
    MP -> "MNP",
    MQ -> "MTQ",
    MR -> "MRT",
    MS -> "MSR",
    MT -> "MLT",
    MU -> "MUS",
    MV -> "MDV",
    MW -> "MWI",
    MX -> "MEX",
    MY -> "MYS",
    MZ -> "MOZ",
    NA -> "NAM",
    NC -> "NCL",
    NE -> "NER",
    NF -> "NFK",
    NG -> "NGA",
    NI -> "NIC",
    NL -> "NLD",
    NO -> "NOR",
    NP -> "NPL",
    NR -> "NRU",
    NU -> "NIU",
    NZ -> "NZL",
    OM -> "OMN",
    PA -> "PAN",
    PE -> "PER",
    PF -> "PYF",
    PG -> "PNG",
    PH -> "PHL",
    PK -> "PAK",
    PL -> "POL",
    PM -> "SPM",
    PN -> "PCN",
    PR -> "PRI",
    PS -> "PSE",
    PT -> "PRT",
    PW -> "PLW",
    PY -> "PRY",
    QA -> "QAT",
    RE -> "REU",
    RO -> "ROU",
    RS -> "SRB",
    RU -> "RUS",
    RW -> "RWA",
    SA -> "SAU",
    SB -> "SLB",
    SC -> "SYC",
    SD -> "SDN",
    SE -> "SWE",
    SG -> "SGP",
    SH -> "SHN",
    SI -> "SVN",
    SJ -> "SJM",
    SK -> "SVK",
    SL -> "SLE",
    SM -> "SMR",
    SN -> "SEN",
    SO -> "SOM",
    SR -> "SUR",
    SS -> "SSD",
    ST -> "STP",
    SV -> "SLV",
    SX -> "SXM",
    SY -> "SYR",
    SZ -> "SWZ",
    TC -> "TCA",
    TD -> "TCD",
    TF -> "ATF",
    TG -> "TGO",
    TH -> "THA",
    TJ -> "TJK",
    TK -> "TKL",
    TL -> "TLS",
    TM -> "TKM",
    TN -> "TUN",
    TO -> "TON",
    TR -> "TUR",
    TT -> "TTO",
    TV -> "TUV",
    TW -> "TWN",
    TZ -> "TZA",
    UA -> "UKR",
    UG -> "UGA",
    UK -> "GBR",
    UM -> "UMI",
    US -> "USA",
    UY -> "URY",
    UZ -> "UZB",
    VA -> "VAT",
    VC -> "VCT",
    VE -> "VEN",
    VG -> "VGB",
    VI -> "VIR",
    VN -> "VNM",
    VU -> "VUT",
    WF -> "WLF",
    WS -> "WSM",
    YE -> "YEM",
    YT -> "MYT",
    ZA -> "ZAF",
    ZM -> "ZMB",
    ZW -> "ZWE",
    Unknown -> "XXX"
  )

  given Show[CountryCode] = Show.fromToString

  val codeMap = {
    val fromName = fullNames.map(c => c._1.toString() -> c._1).toMap
    val fromAlpha3 = alpha3.map(c => c._2 -> c._1).toMap

    fromName ++ fromAlpha3

  }

  def toDomain(s: String): CountryCode =
    codeMap.getOrElse(s.toUpperCase().trim(), Unknown)
}
